# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 030b22f68f311fbdcc45b537477bd4cfdce8bdf230b3991a7c6ded18ae244a739bb4d30c0acc3833c5ce7509e4f47b00e831368a53f3927d153aee6d5bde6094

test:
  secret_key_base: ffd3e35cb7cde166efd5ec41c3dae7835b6caae4ddcf991d2e8f57aff7c2e76ea906d68393be43f16eda96b475740f2d642a40d0e30e2def98d1aa562573033a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
